//
// Created by kosenko on 23.01.24.
//

#ifndef BRAIN_CRAFT_SRC_NEURAL_BFO_NODES_COMMUNICATION_STRUCTURES_H
#define BRAIN_CRAFT_SRC_NEURAL_BFO_NODES_COMMUNICATION_STRUCTURES_H

#endif //BRAIN_CRAFT_SRC_NEURAL_BFO_NODES_COMMUNICATION_STRUCTURES_H
