//
// Created by kosenko on 26.01.24.
//

#ifndef BRAIN_CRAFT_SRC_NEURAL_BFO_NODES_INPUT_NODES_H
#define BRAIN_CRAFT_SRC_NEURAL_BFO_NODES_INPUT_NODES_H

#endif //BRAIN_CRAFT_SRC_NEURAL_BFO_NODES_INPUT_NODES_H
