//
// Created by kosenko on 24.01.24.
//

#ifndef BRAIN_CRAFT_SRC_NEURAL_BFO_REGULARIZERS_REGULARIZER_H
#define BRAIN_CRAFT_SRC_NEURAL_BFO_REGULARIZERS_REGULARIZER_H

#endif //BRAIN_CRAFT_SRC_NEURAL_BFO_REGULARIZERS_REGULARIZER_H
